version: "3.4"
services:
  frontend-server:
    container_name: "clipboard-frontend-prod-server"
    image: orenoid/clipboard-frontend-prod
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: production-server
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
        - clipboard
    depends_on:
      - backend-server

  backend-server:
    container_name: "clipboard-backend-prod-server"
    image: orenoid/clipboard-backend-prod
    environment: 
      FLASK_CONFIG: production
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: prod
    networks:
        - clipboard
    volumes:
      - backend-data:/code/data
    ports:
      - "5000:5000"
    env_file: 
      - ./conf/backend-prod.example.env
    depends_on: 
      - backend-database

  backend-database:
    container_name: "clipboard-backend-prod-database"
    image: mysql:5.7.30
    volumes: 
      - backend-database:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks: 
      - clipboard
    ports: 
      - "3309:3306"
    env_file: 
      - ./conf/mysql.example.env

volumes:
  backend-data:
  backend-database:

networks:
    clipboard: