version: "3.4"
services:
  frontend-server:
    container_name: "clipboard-frontend-prod-server"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: production-server
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
        - clipboard
    depends_on:
      - backend-server

  backend-server:
    container_name: "clipboard-backend-prod-server"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: prod
    volumes:
      - backend-data:/code/data
    networks:
    - clipboard
    ports:
      - "5000:5000"

volumes:
  backend-data:

networks:
    clipboard: