"""empty message

Revision ID: d754e28f94d7
Revises: 1ea287df18aa
Create Date: 2020-06-01 13:56:04.421523

"""
import sqlalchemy as sa
from alembic import op
import datetime

# revision identifiers, used by Alembic.
revision = '0002_d754e28f94d7'
down_revision = '0001_1ea287df18aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute(f'update clip set created_at = "{datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}"')
    op.alter_column('clip', 'created_at', nullable=False, existing_nullable=True, existing_type=sa.DateTime())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clip', 'created_at')
    # ### end Alembic commands ###
